apiVersion: v1
kind: Secret
metadata:
  name: ai-market-studio-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "dummy"
  EXCHANGERATE_API_KEY: "da38a6e0ae77494247ec87cd6abe8823"
  FRED_API_KEY: "49902bd505135a5970742c278a2584a7"
